# Generated by Django 6.0.4 on 2026-04-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comercial_name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('lote', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('pharmaceutic_form', models.CharField(max_length=100)),
                ('cum', models.CharField(max_length=100)),
                ('final_date', models.DateField()),
            ],
        ),
    ]
