version: "3.9"

services:
  db:
    image: postgres:17
    container_name: medical_db
    restart: always
    environment:
      POSTGRES_DB: medical_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --locale=C
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .                 # 🔥 incluye TODO el proyecto
      dockerfile: backend/Dockerfile
    container_name: medical_backend
    restart: always
    volumes:
      - .:/app                  # 🔥 necesario para que exista manage.py
    working_dir: /app           # 🔥 donde está manage.py
    environment:
      DB_NAME: medical_db
      DB_USER: postgres
      DB_PASSWORD: "12345"
      DB_HOST: db
      DB_PORT: "5432"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data: